modLoader="javafml"
loaderVersion="[34,)"
license="All rights reserved"

[[mods]]

modId="spicycore"
version="${file.jarVersion}"
displayName="Spicy Core"
credits="Dank memes"
authors="vtsman, came20, ninjabou, tacoguy56, masterzach32"
description='''
	The spiciest core.
'''