[versions]
minecraft = "1.17.1"
mappings = "1.17.1"
fabric-api = "0.37.1+1.17"
fabric-loader = "0.11.6"
fabric-kotlin = "1.6.3+kotlin.1.5.21"
forge = "1.17.1-37.0.22"

[libraries]
fabric-minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }
fabric-api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api" }
fabric-kotlin = { module = "net.fabricmc:fabric-language-kotlin", version.ref = "fabric-kotlin" }
forge-minecraft = { module = "net.minecraftforge:forge", version.ref = "forge" }

[bundles]
fabric-implmentation = ["fabric-loader", "fabric-api", "fabric-kotlin"]
