[versions]
minecraft = "1.17.1"
mappings = "1.17.1"
fabric-loader = "0.11.6"
fabric-api = "0.37.2+1.17"
fabric-kotlin = "1.6.3+kotlin.1.5.21"
fabric-modmenu = "2.0.4"
forge = "1.17.1-37.0.27"
kotlinx-serialization = "1.2.2"

[libraries]
fabric-minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }
fabric-api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api" }
fabric-kotlin = { module = "net.fabricmc:fabric-language-kotlin", version.ref = "fabric-kotlin" }
forge-minecraft = { module = "net.minecraftforge:forge", version.ref = "forge" }
kotlinx-serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kotlinx-serialization" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
fabric-modmenu = { module = "com.terraformersmc:modmenu", version.ref = "fabric-modmenu" }

[bundles]
fabric-implmentation = ["fabric-loader", "fabric-api", "fabric-kotlin"]
